### PR TITLE
Fix DB tests

### LINKED ISSUE #53: Fix broken DB tests

### LINKED ISSUE #54: Move DB tests into /server/db
Move DB tests to /server/db and make TS ignore them

### PR DESCRIPTION
**Pull request by paloobi**
## Description
Fix the broken DB tests and move them into the `/server/db/` folder

Also removed the obsolete Node Server tests.

## Related Issue

Closes #53 
Closes #54 

## Checklist
- [X] Created tests which fail without the change (if possible)
- [X] Confirmed all tests are passing

## How Has This Been Tested?

All tests now passing

### Costumes
Screenshot 2023-09-28 at 9 43 16 AM

### Customers
Screenshot 2023-09-28 at 9 43 12 AM

### Orders
Screenshot 2023-09-28 at 9 43 06 AM

### Orders Costumes
Screenshot 2023-09-28 at 9 44 55 AM

### CODE REVIEW

**Comment by dyazdani** [comment]
I noticed the endpoint tests were deleted. Was that intentional? Did you want me to start from scratch making them TS files?

**Comment by paloobi** [comment]
@dyazdani yes, that was intentional, the hope is we can get the new API tests into TS. I think it will be easier to start from scratch. But feel free to refer back to the older commits with the node server tests to use them as reference (eg. to copy-paste as a starting point)

But let me know if you prefer I leave them

**Comment by dyazdani** [comment]
@paloobi No, deleting them is fine. I figured you wanted us to start from scratch, but I wanted to make sure.

**Review by dyazdani — APPROVED** [review]
LGTM

**Comment by paloobi** [comment]
I was hitting test failures on subsequent runs due to "duplicate keys" in the DB which told me cleanup wasn't working as expected.

So I updated the tests to dropTables (also refactored to make a dropTables function)

Now they pass even when run multiple times in a row:
Screenshot 2023-09-28 at 10 23 51 AM
Screenshot 2023-09-28 at 10 23 56 AM
Screenshot 2023-09-28 at 10 24 01 AM

**Review by dyazdani — APPROVED** [review]
As long as all the tests are passing, it looks good to me.

**Comment by dyazdani** [comment]
So I'm actually still getting a lot of duplicate key and no relation errors. If I run tests with --runInBand argument to make them sequential, they go away, but that seems like a janky fix. And even then I get an error with the timestamps:
Screen Shot 2023-09-28 at 11 13 59

Are you experiencing this too?

**Comment by paloobi** [comment]
No I had to change all the timestamps to get it to pass. This is a pretty big issue as it means the test is now flaky and will pass/fail differently depending on machine. It would be best if the timestamps were not hard-coded like this.

**Pull request closed without merging**
